name: Build/release

on: push

jobs:
  release:
    name: Build Electron
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16

      - name: npm install
        run: |
          npm install
      - name: build windows app
        if: matrix.os == 'windows-latest'
        run: |
          npm run nsis

